---
title: Maskarada
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: teatr.maskarada@gmail.com
description: 'Teatr i Wypożyczalnia Kostiumów Karnawałowych Maskarada zapewnią Twojemu
  dziecku nalepszą rozrywkę połączoną z edukacją teatralną. Przynosimy uśmiech już
  od 10 lat!

'
baseurl: ''
url: http://www.maskarada.waw.pl
exclude:
- vendor
markdown: kramdown
cloudinary:
  cloud_name: maskarada
