# Site settings
title: Maskarada
email: teatr.maskarada@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Teatr i Wypożyczalnia Kostiumów Karnawałowych Maskarada zapewnią Twojemu dziecku nalepszą rozrywkę połączoną z edukacją teatralną. Przynosimy uśmiech już od 10 lat!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.maskarada.waw.pl" # the base hostname & protocol for your site
exclude: [vendor]

# Build settings
markdown: kramdown
