---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Teatr - repertuary
- type: document
  path: _data/spektakle/spektakle.yml
  label: Nazwy spektakli
- type: document
  path: _data/spektakle/listopad.yml
  label: Listopad
- type: document
  path: _data/spektakle/grudzien.yml
  label: Grudzien
- type: document
  path: _data/spektakle/styczen.yml
  label: Styczen
- type: document
  path: _data/spektakle/luty.yml
  label: Luty
- type: heading
  label: Teatr - strony
- type: document
  path: t/index.md
  label: Strona główna
- type: document
  path: t/repertuar.md
  label: Repertuar
- type: document
  path: t/bilety.md
  label: Bilety
- type: document
  path: t/onas.md
  label: O nas
- type: document
  path: t/warsztaty.md
  label: Warsztaty
- type: document
  path: t/kontakt.md
  label: Kontakt
- type: heading
  label: Wypożyczalnia - strony
- type: document
  path: w/index.html
  label: Strona główna
- type: document
  path: w/cennik.html
  label: Cennik
- type: document
  path: w/kontakt.html
  label: Kontakt
- type: heading
  label: Bazy danych
- type: directory
  path: _data
  label: Wszystkie bazy danych
  create: all
  match: "**/*"
  new_doc_ext: yml
- type: directory
  path: ''
  label: Wszystkie pliki
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site
  publish_env:
  - JEKYLL_ENV=production
  output_directory: _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
